In [2]:
import pandas as pd 
import numpy as np 
import warnings 
warnings.filterwarnings(action='ignore')

In [3]:
iris = pd.read_csv(r'/Users/surajsamal/Desktop/Iris.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [8]:
for i in iris:
    print(i,iris[i].unique())

Id [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150]
SepalLengthCm [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]
SepalWidthCm [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]
PetalLengthCm [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.

In [9]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [10]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [11]:
iris.shape

(150, 6)

In [12]:
iris.columns = ['id','sl','sw','pl','pw','flower']
iris.head()

id   sl   sw   pl   pw       flower
0   1  5.1  3.5  1.4  0.2  Iris-setosa
1   2  4.9  3.0  1.4  0.2  Iris-setosa
2   3  4.7  3.2  1.3  0.2  Iris-setosa
3   4  4.6  3.1  1.5  0.2  Iris-setosa
4   5  5.0  3.6  1.4  0.2  Iris-setosa

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
iris.flower=le.fit_transform(iris.flower)

In [15]:
iris.flower.unique()

array([0, 1, 2])

In [16]:
ip = iris.drop('flower',axis=1)
op = iris.flower

In [17]:
from keras.utils import to_categorical
op = to_categorical(op,3)

In [18]:
op

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(ip,op,test_size = 0.2)

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [25]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [27]:
model = Sequential()
#input layer
model.add(Dense(50,input_dim = 5,activation = 'relu'))
#hidden layers
model.add(Dense(30,activation = 'relu'))
model.add(Dense(20,activation = 'relu'))
#output layer
model.add(Dense(3,activation = 'softmax'))
model.compile(Adam(learning_rate = 0.03),loss = 'categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 50)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 20)             │           620 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            63 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,513 (9.82 KB)

 Trainable params: 2,513 (9.82 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
h = model.fit(x_train,y_train,epochs=20,validation_data=(x_test,y_test))

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5125 - loss: 0.9003 - val_accuracy: 0.9000 - val_loss: 0.3046
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8717 - loss: 0.3003 - val_accuracy: 0.9000 - val_loss: 0.3390
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9858 - loss: 0.0593 - val_accuracy: 0.9333 - val_loss: 0.4341
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0235 - val_accuracy: 0.9333 - val_loss: 0.4349
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.9000 - val_loss: 0.4517
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.7637e-04 - val_accuracy: 0.9000 - val_loss: 0.4744
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.0889e-04 - val_accuracy: 0.9000 - val_loss: 0.3541
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.8253e-05 - val_accuracy: 0.9667 - val_loss: 0.

In [35]:
yp = model.predict(x_test)
yp

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([[1.35286739e-16, 1.81173348e-07, 9.99999762e-01],
       [1.00000000e+00, 2.97255963e-24, 0.00000000e+00],
       [2.21217775e-17, 4.89221334e-01, 5.10778666e-01],
       [9.00780470e-16, 9.31511895e-05, 9.99906957e-01],
       [1.16154085e-14, 2.73123010e-06, 9.99997258e-01],
       [5.22602205e-11, 3.03229690e-02, 9.69677031e-01],
       [3.60568736e-12, 2.53705412e-01, 7.46294558e-01],
       [7.55407064e-16, 1.00000000e+00, 1.38761810e-12],
       [1.00000000e+00, 2.55911974e-29, 0.00000000e+00],
       [1.32293478e-25, 5.12519816e-14, 1.00000000e+00],
       [1.91316304e-15, 1.00000000e+00, 7.18451991e-13],
       [1.36607684e-15, 1.00000000e+00, 1.26957811e-13],
       [1.00000000e+00, 4.12363603e-25, 0.00000000e+00],
       [1.00000000e+00, 4.13101429e-28, 0.00000000e+00],
       [1.09179784e-03, 9.98908162e-01, 1.40628385e-26],
       [1.19300316e-11, 1.00000000e+00, 1.75375492e-09],
       [9.84018707e-14, 1.00000000e+00, 7.45494083e-11],
       [1.00000000e+00, 2.85061

In [37]:
c=[]
for i in yp:
    c.append(np.argmax (i))
print(c)

[2, 0, 2, 2, 2, 2, 2, 1, 0, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 0, 2]


In [39]:
c1 = []

In [41]:
for i in y_test:
    c1.append(np.argmax(i))
print(c1)    

[2, 0, 2, 2, 2, 2, 2, 1, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 0, 2]


In [43]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

In [45]:
acc = accuracy_score(c,c1)
pre=precision_score(c,c1,average='macro')
recall=recall_score(c,c1,average='macro')
f1 = f1_score(c,c1,average='macro')
print('acc=',acc)
print('pre=',pre)
print('recall=',recall)
print('f1=',f1)

acc= 0.9666666666666667
pre= 0.9629629629629629
recall= 0.9629629629629629
f1= 0.9607843137254902
